# Generated by Django 4.1.3 on 2022-11-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_information',
            name='cell',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='retail_information',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
